require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0
  Exclude:
    - 'db/**/*'
    - 'bin/**'
    - 'Guardfile'

Style/Documentation:
  Enabled: false